### ISSUE TITLE
maybe rename python example

### ISSUE THREAD

**Issue by aybabtme** [natefinch/pie#11]
Somehow I ended up with the python example compiled in my `$GOPATH/bin`, which is part of my `$PATH`. This led to this super confusing but hilarious interaction with my shell:

```
$ python
[master log] 2016/04/20 15:08:28 Creating plugin
[master log] 2016/04/20 15:08:28 Create error: fork/exec ./plugin.py: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x78855]

goroutine 11 [running]:
panic(0x401340, 0xc82000a0e0)
    /Users/antoine/go/src/runtime/panic.go:464 +0x3e6
net/rpc.(*Client).send(0x0, 0xc82013e000)
    /Users/antoine/go/src/net/rpc/client.go:72 +0x3a5
net/rpc.(*Client).Go(0x0, 0x4893d0, 0x3, 0x33fce0, 0xc82012a000, 0x3314c0, 0xc820126000, 0xc82012c000, 0xc820028670)
    /Users/antoine/go/src/net/rpc/client.go:309 +0x12a
net/rpc.(*Client).Call(0x0, 0x4893d0, 0x3, 0x33fce0, 0xc82012a000, 0x3314c0, 0xc820126000, 0x0, 0x0)
    /Users/antoine/go/src/net/rpc/client.go:315 +0x9c
main.plug.Add(0x0, 0x5, 0x6, 0x0, 0x0, 0x0)
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:73 +0x139
main.doCall(0x5, 0x6, 0xc820016300, 0xc8200300d0)
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:42 +0x5b
created by main.loopStart
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:54 +0xc6
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x78855]

goroutine 23 [running]:
panic(0x401340, 0xc82000a0e0)
    /Users/antoine/go/src/runtime/panic.go:464 +0x3e6
net/rpc.(*Client).send(0x0, 0xc820164000)
    /Users/antoine/go/src/net/rpc/client.go:72 +0x3a5
net/rpc.(*Client).Go(0x0, 0x4893d0, 0x3, 0x33fce0, 0xc82015c000, 0x3314c0, 0xc820152000, 0xc82015e000, 0xc820123e70)
    /Users/antoine/go/src/net/rpc/client.go:309 +0x12a
net/rpc.(*Client).Call(0x0, 0x4893d0, 0x3, 0x33fce0, 0xc82015c000, 0x3314c0, 0xc820152000, 0x0, 0x0)
    /Users/antoine/go/src/net/rpc/client.go:315 +0x9c
main.plug.Add(0x0, 0x10, 0x11, 0x0, 0x0, 0x0)
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:73 +0x139
main.doCall(0x10, 0x11, 0xc820016300, 0xc8200300d0)
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:42 +0x5b
created by main.loopStart
    /Users/antoine/gocode/src/github.com/digitalocean/doctl/vendor/github.com/natefinch/pie/examples/python/master.go:54 +0xc6

$ which python
/Users/antoine/gocode/bin/python

$ rm /Users/antoine/gocode/bin/python
```

Anyhow I just thought maybe you'd rename the `example/python` to something like `example/python-plugins`? I can send a PR if you agree.

**Comment by natefinch** [comment]
Totally agree... come to think of it, I did the same thing, but for some reason never fixed it.  Please do make up a PR, thanks!
